version: '1'
services:
     web:
        build: .
        ports:
          - 8080:8080
        depends_on:
          - db
     db:
        container_name: postgres
        image: postgres:9.5
        volumes:
          - postgres_db:/var/lib/postgresql/data
        environment:
          - POSTGRES_PASSWORD=changeit
          - POSTGRES_USER=changeit
          - POSTGRES_DB=securities
          - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
          - 5432:5432
volumes:
    postgres_db: {}